import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Layouts/Sidebar";
import Header from "@/components/Layouts/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>

    <div className="flex min-h-screen w-full">
      <Sidebar />

      <div className="flex-1 min-w-0 bg-gray-100 pl-64">
        <Header />
        {children}
      </div>
    </div>
      </body>
    </html>
  );
}
